#!/usr/bin/env bash
# install-macos-app.sh — create fpdf.app and install it to ~/Applications
#
# Usage:
#   ./scripts/install-macos-app.sh
#   ./scripts/install-macos-app.sh --dest /Applications   # install system-wide
#
# The app opens a Terminal window and runs `scripts/fpdf --open`, which starts
# the local web server and launches the file picker in your default browser.
# Close the Terminal window to stop the server.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_dir="$(dirname "$script_dir")"

dest="${HOME}/Applications"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dest) dest="$2"; shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

app_path="${dest}/fpdf.app"

# Write a temporary AppleScript that bakes in the repo path.
tmpscript="$(mktemp /tmp/fpdf_app_XXXXXX.applescript)"
trap 'rm -f "$tmpscript"' EXIT

cat > "$tmpscript" <<APPLESCRIPT
-- fpdf.app — generated by install-macos-app.sh
-- repo: ${repo_dir}
property repoPath : "${repo_dir}"

on run
    tell application "Terminal"
        activate
        do script "cd " & quoted form of repoPath & " && ./scripts/fpdf --open"
    end tell
end run
APPLESCRIPT

mkdir -p "$dest"
osacompile -o "$app_path" "$tmpscript"

echo "Installed: ${app_path}"
echo "Double-click it in Finder (or open \"${app_path}\") to launch fpdf."
