name: Publish to npm

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm-production
    permissions:
      contents: read
      id-token: write # required for provenance
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Validate & Build Project
        run: pnpm run check && pnpm run test && pnpm run build
        
      - name: Publish to npm
        run: pnpm publish --ignore-scripts --no-git-checks --access public --provenance
